/* Project: Vehicular Cloud Real Time System (VCRTS)
 * Class: Owner.java
 * Authors: Group 2 (Justin Cracchiolo, Lauren Rodriguez, David Choi, Tristan Huertas, Ivan Lin, Anthony Vallejo, and Sebastian Villavicencio)
 * Date: February 2026
 * The Owner class represents a vehicle provider in the VCRTS system. It extends the User class and stores information specific to vehicle
 * owners, including their registered vehicles and approximate residency time. Owners can add vehicles to the system and manage their availability.
 */

package classes;

// ---------------------------------------------------------------
//this class represents a user of the system(specifically owner)
import java.util.ArrayList;

// ---------------------------------------------------------------
//The Owner class extends User to add additional fields for car owners, such as a list of their vehicles and their approximate residency time. 
// It also includes methods to add vehicles and retrieve the owner's information.

public class Owner extends User {
    private ArrayList<Vehicle> ownerVehicles = new ArrayList<>();
    private ArrayList<Job> ownerJobs = new ArrayList<>();
    private String ownerId; 
    private static int increment = 0;

    // ---------------------------------------------------------------
    // constructor for the owner class; utilizes the constructor of the User class
    // to set the username and password.
    public Owner(String username, String password) {
        this(username, password, "");
    }

    public Owner(String username, String password, String email) {
        super(username, password, email, "Owner");
        
        //this.approximateResidencyTime = approximateResidencyTime;
        increment++;

        this.ownerId = Integer.toString(increment); // set ownerId to the userId generated by the User class constructor
    }

    // ---------------------------------------------------------------
    // this method returns the owner's ID for a specific owner.
    public String getOwnerId() {
        return ownerId; 
    }

    // ---------------------------------------------------------------
    // adds a vehicle to the owner's list of vehicles
    public void addVehicle(Vehicle vehicle) {
        ownerVehicles.add(vehicle);
    }

    // ---------------------------------------------------------------
    // returns => owner's list of vehicles
    public ArrayList<Vehicle> getVehicles() {
        return ownerVehicles;
    }

    // ---------------------------------------------------------------

    // adds a job to the owner's list of jobs
    public void addJob(Job job) {
        ownerJobs.add(job);
    }

    // ---------------------------------------------------------------
    // returns => owner's list of jobs
    public ArrayList<Job> getJobs() {
        return ownerJobs;
    }
}
